// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlLn2tjcE8JSN89yB3EXEzitiLzV_Ft4',
    appId: '1:1026820419236:web:cecf46246e8bf069314031',
    messagingSenderId: '1026820419236',
    projectId: 'pelion-naval-tour-neochori',
    authDomain: 'pelion-naval-tour-neochori.firebaseapp.com',
    storageBucket: 'pelion-naval-tour-neochori.firebasestorage.app',
    measurementId: 'G-7EHV8F8PEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArf06byoObDGuj7-hdJeYRD5UlvWiAo4',
    appId: '1:1026820419236:android:70e3616196ae6fe1314031',
    messagingSenderId: '1026820419236',
    projectId: 'pelion-naval-tour-neochori',
    storageBucket: 'pelion-naval-tour-neochori.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKbNv51ClBx3kDRI7JyQGLP5jlnsf0ii8',
    appId: '1:1026820419236:ios:ad140f9d9f73d408314031',
    messagingSenderId: '1026820419236',
    projectId: 'pelion-naval-tour-neochori',
    storageBucket: 'pelion-naval-tour-neochori.firebasestorage.app',
    iosBundleId: 'com.example.pilionNavalTourNeochori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKbNv51ClBx3kDRI7JyQGLP5jlnsf0ii8',
    appId: '1:1026820419236:ios:ad140f9d9f73d408314031',
    messagingSenderId: '1026820419236',
    projectId: 'pelion-naval-tour-neochori',
    storageBucket: 'pelion-naval-tour-neochori.firebasestorage.app',
    iosBundleId: 'com.example.pilionNavalTourNeochori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlLn2tjcE8JSN89yB3EXEzitiLzV_Ft4',
    appId: '1:1026820419236:web:0d73f4775d0d91e9314031',
    messagingSenderId: '1026820419236',
    projectId: 'pelion-naval-tour-neochori',
    authDomain: 'pelion-naval-tour-neochori.firebaseapp.com',
    storageBucket: 'pelion-naval-tour-neochori.firebasestorage.app',
    measurementId: 'G-DMZBDRGWLH',
  );
}
